# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225, unique=True)),
                ('Console', models.CharField(max_length=50, unique=True)),
                ('ReleaseDate', models.CharField(max_length=10, unique=True)),
                ('Description', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
