# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameslist',
            name='Description',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
