# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180216_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamesList',
        ),
    ]
